/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.18.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package pl.netia.troubleticket.api;

import pl.netia.troubleticket.model.Error;
import pl.netia.troubleticket.model.Note;
import pl.netia.troubleticket.model.NoteCreateRequest;
import pl.netia.troubleticket.model.TroubleTicket;
import pl.netia.troubleticket.model.TroubleTicketCloseStatusRequest;
import pl.netia.troubleticket.model.TroubleTicketCreateRequest;
import pl.netia.troubleticket.model.TroubleTicketSummary;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Optional;

@Validated
@Tag(name = "TroubleTicket", description = "Operacje na zgłoszeniach Trouble Ticket.")
public interface TroubleTicketApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_CLOSE_TROUBLE_TICKET = "/troubleTicket/{id}";
    /**
     * PATCH /troubleTicket/{id} : Zamknij zgłoszenie Trouble Ticket
     * Umożliwia publicznemu klientowi API zmianę statusu wyłącznie na &#x60;closed&#x60;.  Pozostałe przejścia statusów są poza zakresem tej specyfikacji i muszą być odrzucone jako &#x60;400&#x60;. 
     *
     * @param id Unikalny identyfikator zgłoszenia Trouble Ticket. (required)
     * @param troubleTicketCloseStatusRequest  (required)
     * @return Zgłoszenie zostało zamknięte. (status code 200)
     *         or Żądanie jest niepoprawne lub wykracza poza dozwolony kontrakt v1. (status code 400)
     *         or Brak uwierzytelnienia albo niepoprawny token. (status code 401)
     *         or Użytkownik jest uwierzytelniony, ale nie ma wymaganych uprawnień do wykonania operacji. (status code 403)
     *         or Zgłoszenie nie istnieje albo nie jest widoczne w tenant scope użytkownika. (status code 404)
     */
    @Operation(
        operationId = "closeTroubleTicket",
        summary = "Zamknij zgłoszenie Trouble Ticket",
        description = "Umożliwia publicznemu klientowi API zmianę statusu wyłącznie na `closed`.  Pozostałe przejścia statusów są poza zakresem tej specyfikacji i muszą być odrzucone jako `400`. ",
        tags = { "TroubleTicket" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Zgłoszenie zostało zamknięte.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = TroubleTicket.class), examples = {
                    @ExampleObject(
                        name = "TroubleTicketClosedResponse",
                        value = "{\"id\":\"TT-2026-000001\",\"externalId\":\"OK-123456\",\"serviceId\":987654321,\"description\":\"Brak transmisji danych dla usługi klienta.\",\"status\":\"closed\",\"notes\":[{\"id\":\"NOTE-000001\",\"text\":\"Zgłoszenie utworzone przez konto API partnera.\",\"date\":\"2026-03-19T10:15:00Z\"},{\"id\":\"NOTE-000002\",\"text\":\"Klient potwierdził zamknięcie zgłoszenia.\",\"date\":\"2026-03-19T11:00:00Z\"}]}"
                    )
                })

            }),
            @ApiResponse(responseCode = "400", description = "Żądanie jest niepoprawne lub wykracza poza dozwolony kontrakt v1.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "BadRequestError",
                        value = "{\"code\":\"VALIDATION_ERROR\",\"message\":\"Pole status ma niedozwoloną wartość dla tej operacji.\",\"requestId\":\"req-9f8e7d6c\"}"
                    )
                })

            }),
            @ApiResponse(responseCode = "401", description = "Brak uwierzytelnienia albo niepoprawny token.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "UnauthorizedError",
                        value = "{\"code\":\"UNAUTHORIZED\",\"message\":\"Brak poprawnego Bearer tokenu.\",\"requestId\":\"req-9f8e7d6c\"}"
                    )
                })

            }),
            @ApiResponse(responseCode = "403", description = "Użytkownik jest uwierzytelniony, ale nie ma wymaganych uprawnień do wykonania operacji.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "ForbiddenError",
                        value = "{\"code\":\"FORBIDDEN\",\"message\":\"Użytkownik nie ma uprawnień do wykonania tej operacji.\",\"requestId\":\"req-9f8e7d6c\"}"
                    )
                })

            }),
            @ApiResponse(responseCode = "404", description = "Zgłoszenie nie istnieje albo nie jest widoczne w tenant scope użytkownika.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "TroubleTicketNotFoundError",
                        value = "{\"code\":\"TROUBLE_TICKET_NOT_FOUND\",\"message\":\"Zgłoszenie nie istnieje albo nie jest widoczne w tenant scope użytkownika.\",\"requestId\":\"req-9f8e7d6c\"}"
                    )
                })

            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = TroubleTicketApi.PATH_CLOSE_TROUBLE_TICKET,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<TroubleTicket> closeTroubleTicket(
        @NotNull @Size(min = 1) @Parameter(name = "id", description = "Unikalny identyfikator zgłoszenia Trouble Ticket.", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @Parameter(name = "TroubleTicketCloseStatusRequest", description = "", required = true) @Valid @RequestBody TroubleTicketCloseStatusRequest troubleTicketCloseStatusRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"notes\" : [ { \"date\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : \"id\", \"text\" : \"text\" }, { \"date\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : \"id\", \"text\" : \"text\" } ], \"externalId\" : \"externalId\", \"description\" : \"description\", \"id\" : \"id\", \"serviceId\" : 1, \"status\" : \"new\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"requestId\" : \"requestId\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"requestId\" : \"requestId\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"requestId\" : \"requestId\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"requestId\" : \"requestId\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_CREATE_TROUBLE_TICKET = "/troubleTicket";
    /**
     * POST /troubleTicket : Utwórz zgłoszenie Trouble Ticket
     * Tworzy nowe zgłoszenie przypisane do tenant scope wynikającego z Bearer tokenu.  Klient publicznego API może przekazać wyłącznie status &#x60;new&#x60;. Jeżeli istnieje już zgłoszenie o tym samym &#x60;(tenantId, externalId)&#x60;, API zwraca &#x60;200 OK&#x60; z istniejącą reprezentacją zasobu.  Dla nowo utworzonego zgłoszenia odpowiedź może już zwracać status &#x60;acknowledged&#x60;, zgodnie z przepływem przetwarzania po stronie SOZ. 
     *
     * @param troubleTicketCreateRequest  (required)
     * @return Zgłoszenie utworzone. (status code 201)
     *         or Zwrócono istniejące zgłoszenie na podstawie idempotencji &#x60;(tenantId, externalId)&#x60;. (status code 200)
     *         or Żądanie jest niepoprawne lub wykracza poza dozwolony kontrakt v1. (status code 400)
     *         or Brak uwierzytelnienia albo niepoprawny token. (status code 401)
     *         or Użytkownik jest uwierzytelniony, ale nie ma wymaganych uprawnień do wykonania operacji. (status code 403)
     *         or Wskazana usługa nie istnieje, nie jest aktywna albo nie należy do tenant scope użytkownika. (status code 404)
     */
    @Operation(
        operationId = "createTroubleTicket",
        summary = "Utwórz zgłoszenie Trouble Ticket",
        description = "Tworzy nowe zgłoszenie przypisane do tenant scope wynikającego z Bearer tokenu.  Klient publicznego API może przekazać wyłącznie status `new`. Jeżeli istnieje już zgłoszenie o tym samym `(tenantId, externalId)`, API zwraca `200 OK` z istniejącą reprezentacją zasobu.  Dla nowo utworzonego zgłoszenia odpowiedź może już zwracać status `acknowledged`, zgodnie z przepływem przetwarzania po stronie SOZ. ",
        tags = { "TroubleTicket" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Zgłoszenie utworzone.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = TroubleTicket.class), examples = {
                    @ExampleObject(
                        name = "TroubleTicketCreatedResponse",
                        value = "{\"id\":\"TT-2026-000001\",\"externalId\":\"OK-123456\",\"serviceId\":987654321,\"description\":\"Brak transmisji danych dla usługi klienta.\",\"status\":\"acknowledged\",\"notes\":[{\"id\":\"NOTE-000001\",\"text\":\"Zgłoszenie utworzone przez konto API partnera.\",\"date\":\"2026-03-19T10:15:00Z\"}]}"
                    )
                })

            }),
            @ApiResponse(responseCode = "200", description = "Zwrócono istniejące zgłoszenie na podstawie idempotencji `(tenantId, externalId)`.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = TroubleTicket.class), examples = {
                    @ExampleObject(
                        name = "TroubleTicketExistingResponse",
                        value = "{\"id\":\"TT-2026-000001\",\"externalId\":\"OK-123456\",\"serviceId\":987654321,\"description\":\"Brak transmisji danych dla usługi klienta.\",\"status\":\"inProgress\",\"notes\":[{\"id\":\"NOTE-000001\",\"text\":\"Zgłoszenie utworzone przez konto API partnera.\",\"date\":\"2026-03-19T10:15:00Z\"},{\"id\":\"NOTE-000002\",\"text\":\"Weryfikacja zgłoszenia w toku.\",\"date\":\"2026-03-19T10:20:00Z\"}]}"
                    )
                })

            }),
            @ApiResponse(responseCode = "400", description = "Żądanie jest niepoprawne lub wykracza poza dozwolony kontrakt v1.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "BadRequestError",
                        value = "{\"code\":\"VALIDATION_ERROR\",\"message\":\"Pole status ma niedozwoloną wartość dla tej operacji.\",\"requestId\":\"req-9f8e7d6c\"}"
                    )
                })

            }),
            @ApiResponse(responseCode = "401", description = "Brak uwierzytelnienia albo niepoprawny token.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "UnauthorizedError",
                        value = "{\"code\":\"UNAUTHORIZED\",\"message\":\"Brak poprawnego Bearer tokenu.\",\"requestId\":\"req-9f8e7d6c\"}"
                    )
                })

            }),
            @ApiResponse(responseCode = "403", description = "Użytkownik jest uwierzytelniony, ale nie ma wymaganych uprawnień do wykonania operacji.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "ForbiddenError",
                        value = "{\"code\":\"FORBIDDEN\",\"message\":\"Użytkownik nie ma uprawnień do wykonania tej operacji.\",\"requestId\":\"req-9f8e7d6c\"}"
                    )
                })

            }),
            @ApiResponse(responseCode = "404", description = "Wskazana usługa nie istnieje, nie jest aktywna albo nie należy do tenant scope użytkownika.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "ServiceNotFoundError",
                        value = "{\"code\":\"SERVICE_NOT_FOUND\",\"message\":\"Wskazana usługa nie istnieje, nie jest aktywna albo nie należy do tenant scope użytkownika.\",\"requestId\":\"req-9f8e7d6c\"}"
                    )
                })

            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = TroubleTicketApi.PATH_CREATE_TROUBLE_TICKET,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<TroubleTicket> createTroubleTicket(
        @Parameter(name = "TroubleTicketCreateRequest", description = "", required = true) @Valid @RequestBody TroubleTicketCreateRequest troubleTicketCreateRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"notes\" : [ { \"date\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : \"id\", \"text\" : \"text\" }, { \"date\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : \"id\", \"text\" : \"text\" } ], \"externalId\" : \"externalId\", \"description\" : \"description\", \"id\" : \"id\", \"serviceId\" : 1, \"status\" : \"new\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"notes\" : [ { \"date\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : \"id\", \"text\" : \"text\" }, { \"date\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : \"id\", \"text\" : \"text\" } ], \"externalId\" : \"externalId\", \"description\" : \"description\", \"id\" : \"id\", \"serviceId\" : 1, \"status\" : \"new\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"requestId\" : \"requestId\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"requestId\" : \"requestId\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"requestId\" : \"requestId\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"requestId\" : \"requestId\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_TROUBLE_TICKET_BY_ID = "/troubleTicket/{id}";
    /**
     * GET /troubleTicket/{id} : Pobierz pojedyncze zgłoszenie Trouble Ticket
     * Zwraca pełną reprezentację zgłoszenia widocznego dla uwierzytelnionego użytkownika.  tenant scope wynika wyłącznie z Bearer tokenu. Dla zasobu nieistniejącego albo niewidocznego w tenant scope należy zwrócić &#x60;404&#x60;. 
     *
     * @param id Unikalny identyfikator zgłoszenia Trouble Ticket. (required)
     * @return Pełna reprezentacja zgłoszenia. (status code 200)
     *         or Brak uwierzytelnienia albo niepoprawny token. (status code 401)
     *         or Użytkownik jest uwierzytelniony, ale nie ma wymaganych uprawnień do wykonania operacji. (status code 403)
     *         or Zgłoszenie nie istnieje albo nie jest widoczne w tenant scope użytkownika. (status code 404)
     */
    @Operation(
        operationId = "getTroubleTicketById",
        summary = "Pobierz pojedyncze zgłoszenie Trouble Ticket",
        description = "Zwraca pełną reprezentację zgłoszenia widocznego dla uwierzytelnionego użytkownika.  tenant scope wynika wyłącznie z Bearer tokenu. Dla zasobu nieistniejącego albo niewidocznego w tenant scope należy zwrócić `404`. ",
        tags = { "TroubleTicket" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Pełna reprezentacja zgłoszenia.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = TroubleTicket.class), examples = {
                    @ExampleObject(
                        name = "TroubleTicketResponse",
                        value = "{\"id\":\"TT-2026-000001\",\"externalId\":\"OK-123456\",\"serviceId\":987654321,\"description\":\"Brak transmisji danych dla usługi klienta.\",\"status\":\"resolved\",\"notes\":[{\"id\":\"NOTE-000001\",\"text\":\"Zgłoszenie utworzone przez konto API partnera.\",\"date\":\"2026-03-19T10:15:00Z\"},{\"id\":\"NOTE-000002\",\"text\":\"Potwierdzono diagnozę po stronie operatora infrastruktury.\",\"date\":\"2026-03-19T10:30:00Z\"}]}"
                    )
                })

            }),
            @ApiResponse(responseCode = "401", description = "Brak uwierzytelnienia albo niepoprawny token.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "UnauthorizedError",
                        value = "{\"code\":\"UNAUTHORIZED\",\"message\":\"Brak poprawnego Bearer tokenu.\",\"requestId\":\"req-9f8e7d6c\"}"
                    )
                })

            }),
            @ApiResponse(responseCode = "403", description = "Użytkownik jest uwierzytelniony, ale nie ma wymaganych uprawnień do wykonania operacji.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "ForbiddenError",
                        value = "{\"code\":\"FORBIDDEN\",\"message\":\"Użytkownik nie ma uprawnień do wykonania tej operacji.\",\"requestId\":\"req-9f8e7d6c\"}"
                    )
                })

            }),
            @ApiResponse(responseCode = "404", description = "Zgłoszenie nie istnieje albo nie jest widoczne w tenant scope użytkownika.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "TroubleTicketNotFoundError",
                        value = "{\"code\":\"TROUBLE_TICKET_NOT_FOUND\",\"message\":\"Zgłoszenie nie istnieje albo nie jest widoczne w tenant scope użytkownika.\",\"requestId\":\"req-9f8e7d6c\"}"
                    )
                })

            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = TroubleTicketApi.PATH_GET_TROUBLE_TICKET_BY_ID,
        produces = { "application/json" }
    )
    default ResponseEntity<TroubleTicket> getTroubleTicketById(
        @NotNull @Size(min = 1) @Parameter(name = "id", description = "Unikalny identyfikator zgłoszenia Trouble Ticket.", required = true, in = ParameterIn.PATH) @PathVariable("id") String id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"notes\" : [ { \"date\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : \"id\", \"text\" : \"text\" }, { \"date\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : \"id\", \"text\" : \"text\" } ], \"externalId\" : \"externalId\", \"description\" : \"description\", \"id\" : \"id\", \"serviceId\" : 1, \"status\" : \"new\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"requestId\" : \"requestId\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"requestId\" : \"requestId\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"requestId\" : \"requestId\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_LIST_TROUBLE_TICKETS = "/troubleTicket";
    /**
     * GET /troubleTicket : Listuj zgłoszenia Trouble Ticket
     * Zwraca minimalną listę zgłoszeń widocznych dla uwierzytelnionego użytkownika.  W wersji v1 odpowiedź nie wspiera paginacji ani filtrowania. Zakres danych jest ograniczony do: &#x60;externalId&#x60;, &#x60;serviceId&#x60;, &#x60;description&#x60;, &#x60;status&#x60;. 
     *
     * @return Lista zgłoszeń dostępnych w tenant scope użytkownika. (status code 200)
     *         or Brak uwierzytelnienia albo niepoprawny token. (status code 401)
     *         or Użytkownik jest uwierzytelniony, ale nie ma wymaganych uprawnień do wykonania operacji. (status code 403)
     */
    @Operation(
        operationId = "listTroubleTickets",
        summary = "Listuj zgłoszenia Trouble Ticket",
        description = "Zwraca minimalną listę zgłoszeń widocznych dla uwierzytelnionego użytkownika.  W wersji v1 odpowiedź nie wspiera paginacji ani filtrowania. Zakres danych jest ograniczony do: `externalId`, `serviceId`, `description`, `status`. ",
        tags = { "TroubleTicket" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Lista zgłoszeń dostępnych w tenant scope użytkownika.", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = TroubleTicketSummary.class)), examples = {
                    @ExampleObject(
                        name = "TroubleTicketListResponse",
                        value = "[{\"externalId\":\"OK-123456\",\"serviceId\":987654321,\"description\":\"Brak transmisji danych dla usługi klienta.\",\"status\":\"acknowledged\"},{\"externalId\":\"OK-123457\",\"serviceId\":987654322,\"description\":\"Niestabilne parametry usługi.\",\"status\":\"resolved\"}]"
                    )
                })

            }),
            @ApiResponse(responseCode = "401", description = "Brak uwierzytelnienia albo niepoprawny token.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "UnauthorizedError",
                        value = "{\"code\":\"UNAUTHORIZED\",\"message\":\"Brak poprawnego Bearer tokenu.\",\"requestId\":\"req-9f8e7d6c\"}"
                    )
                })

            }),
            @ApiResponse(responseCode = "403", description = "Użytkownik jest uwierzytelniony, ale nie ma wymaganych uprawnień do wykonania operacji.", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "ForbiddenError",
                        value = "{\"code\":\"FORBIDDEN\",\"message\":\"Użytkownik nie ma uprawnień do wykonania tej operacji.\",\"requestId\":\"req-9f8e7d6c\"}"
                    )
                })

            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = TroubleTicketApi.PATH_LIST_TROUBLE_TICKETS,
        produces = { "application/json" }
    )
    default ResponseEntity<List<TroubleTicketSummary>> listTroubleTickets(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"externalId\" : \"externalId\", \"description\" : \"description\", \"serviceId\" : 1, \"status\" : \"new\" }, { \"externalId\" : \"externalId\", \"description\" : \"description\", \"serviceId\" : 1, \"status\" : \"new\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"requestId\" : \"requestId\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"code\" : \"code\", \"requestId\" : \"requestId\", \"message\" : \"message\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
